version: '3.8'

services:
  app:
    build: .
    container_name: task-management-backend
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://ozgur:ozgur@cluster0.wjju3xz.mongodb.net/task?retryWrites=true&w=majority
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - NODE_ENV=development
    networks:
      - main
    restart: unless-stopped

networks:
  main:
    name: main
    driver: bridge
